-- ============================================================
-- Art Speaks — seed data (ported from lib/data/products.ts)
-- Run AFTER 0001_initial_schema.sql. Safe to re-run: clears both tables first.
-- Category images all share one placeholder for now — swap per-category later
-- with:  update public.categories set image_url = '...' where slug = '...';
-- ============================================================

truncate table public.order_items, public.orders, public.wishlist, public.reviews, public.products, public.categories restart identity cascade;

insert into public.categories (slug, name, accent_color, image_url, sort_order) values
  ('phone-charms', 'Phone Charms', '#FFB7CE', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDKooxAAp8WiC8rTU_TiFkw3Q3nrLdCBRVPYjh2EFCsf35WHNP7KhPFXR-mEwI1OurnjeuWQradKrXNmYC6x3cKvFeNAI9oCGSE_o9uXWqwePWm5QU2N9W4jsGgY9Warmnyx41UYvwbR4yCwqv7koBM4Nhb6_i1fSdvcLW9oDW-tle0BjVsjD_RVPfKF8d_pOVBA784qPGSDAJTjhgplxnljpy_cILywjwUAhiv4uo8hRB1emoO10-0LQ', 1),
  ('keychains-worry-stones', 'Keychains/Worry Stones', '#E0BBE4', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDKooxAAp8WiC8rTU_TiFkw3Q3nrLdCBRVPYjh2EFCsf35WHNP7KhPFXR-mEwI1OurnjeuWQradKrXNmYC6x3cKvFeNAI9oCGSE_o9uXWqwePWm5QU2N9W4jsGgY9Warmnyx41UYvwbR4yCwqv7koBM4Nhb6_i1fSdvcLW9oDW-tle0BjVsjD_RVPfKF8d_pOVBA784qPGSDAJTjhgplxnljpy_cILywjwUAhiv4uo8hRB1emoO10-0LQ', 2),
  ('bookmarks', 'Bookmarks', '#98FFD9', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDKooxAAp8WiC8rTU_TiFkw3Q3nrLdCBRVPYjh2EFCsf35WHNP7KhPFXR-mEwI1OurnjeuWQradKrXNmYC6x3cKvFeNAI9oCGSE_o9uXWqwePWm5QU2N9W4jsGgY9Warmnyx41UYvwbR4yCwqv7koBM4Nhb6_i1fSdvcLW9oDW-tle0BjVsjD_RVPfKF8d_pOVBA784qPGSDAJTjhgplxnljpy_cILywjwUAhiv4uo8hRB1emoO10-0LQ', 3),
  ('paintings', 'Paintings', '#FDFFAB', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDKooxAAp8WiC8rTU_TiFkw3Q3nrLdCBRVPYjh2EFCsf35WHNP7KhPFXR-mEwI1OurnjeuWQradKrXNmYC6x3cKvFeNAI9oCGSE_o9uXWqwePWm5QU2N9W4jsGgY9Warmnyx41UYvwbR4yCwqv7koBM4Nhb6_i1fSdvcLW9oDW-tle0BjVsjD_RVPfKF8d_pOVBA784qPGSDAJTjhgplxnljpy_cILywjwUAhiv4uo8hRB1emoO10-0LQ', 4),
  ('bag-charms', 'Bag Charms', '#FFD3B0', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDKooxAAp8WiC8rTU_TiFkw3Q3nrLdCBRVPYjh2EFCsf35WHNP7KhPFXR-mEwI1OurnjeuWQradKrXNmYC6x3cKvFeNAI9oCGSE_o9uXWqwePWm5QU2N9W4jsGgY9Warmnyx41UYvwbR4yCwqv7koBM4Nhb6_i1fSdvcLW9oDW-tle0BjVsjD_RVPfKF8d_pOVBA784qPGSDAJTjhgplxnljpy_cILywjwUAhiv4uo8hRB1emoO10-0LQ', 5),
  ('fridge-magnets', 'Fridge Magnets', '#AEE2FF', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDKooxAAp8WiC8rTU_TiFkw3Q3nrLdCBRVPYjh2EFCsf35WHNP7KhPFXR-mEwI1OurnjeuWQradKrXNmYC6x3cKvFeNAI9oCGSE_o9uXWqwePWm5QU2N9W4jsGgY9Warmnyx41UYvwbR4yCwqv7koBM4Nhb6_i1fSdvcLW9oDW-tle0BjVsjD_RVPfKF8d_pOVBA784qPGSDAJTjhgplxnljpy_cILywjwUAhiv4uo8hRB1emoO10-0LQ', 6),
  ('tote-bags', 'Tote Bags', '#C7CEEA', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDKooxAAp8WiC8rTU_TiFkw3Q3nrLdCBRVPYjh2EFCsf35WHNP7KhPFXR-mEwI1OurnjeuWQradKrXNmYC6x3cKvFeNAI9oCGSE_o9uXWqwePWm5QU2N9W4jsGgY9Warmnyx41UYvwbR4yCwqv7koBM4Nhb6_i1fSdvcLW9oDW-tle0BjVsjD_RVPfKF8d_pOVBA784qPGSDAJTjhgplxnljpy_cILywjwUAhiv4uo8hRB1emoO10-0LQ', 7),
  ('stickers', 'Stickers', '#FFAAA7', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDKooxAAp8WiC8rTU_TiFkw3Q3nrLdCBRVPYjh2EFCsf35WHNP7KhPFXR-mEwI1OurnjeuWQradKrXNmYC6x3cKvFeNAI9oCGSE_o9uXWqwePWm5QU2N9W4jsGgY9Warmnyx41UYvwbR4yCwqv7koBM4Nhb6_i1fSdvcLW9oDW-tle0BjVsjD_RVPfKF8d_pOVBA784qPGSDAJTjhgplxnljpy_cILywjwUAhiv4uo8hRB1emoO10-0LQ', 8);

insert into public.products
  (slug, name, description, artisan_note, price_cents, currency, stock_count, category_id, images, is_active) values
  ('lavender-whisper-charm', 'Lavender Whisper Charm', 'Each piece is crafted with intention and a sprinkle of studio magic. Small, beautiful objects have the power to turn your daily ritual into a moment of pure creativity.', '"This piece was inspired by the quiet morning light hitting the studio floor. Every detail was mixed and finished by hand to capture that exact translucent quality." — Lucy', 1800, 'USD', 5, (select id from public.categories where slug = 'phone-charms'), array['https://lh3.googleusercontent.com/aida-public/AB6AXuCM3QvU4035pWOGZSDoiSBLXBmQ_EFOplSkv4Nn69hiJoUnuT7dB4exfKdYRn-Y7WZkr9bsA1c8rNh_k_WdBFlYAtFkHP3hXqFMOpMYdbfaAYeYA5Q05jKSbXxTDnKMhOG1REgIsr7sINT7BHUj_O8_6S1XsaY7urDgCuRzPLO8kT5Xnd3WJybuHe9_laxWY93KLGuIGaVCzvcXJx-JSzFk_gYFKbB5mmqlFN1GzBoScM1-WgQzLbfxxA'], true),
  ('midnight-hillside-bookmark', 'Midnight Hillside Bookmark', 'Each piece is crafted with intention and a sprinkle of studio magic. Small, beautiful objects have the power to turn your daily ritual into a moment of pure creativity.', '"This piece was inspired by the quiet morning light hitting the studio floor. Every detail was mixed and finished by hand to capture that exact translucent quality." — Lucy', 1250, 'USD', 12, (select id from public.categories where slug = 'bookmarks'), array['https://lh3.googleusercontent.com/aida-public/AB6AXuDN64zI3Qf-bqROPeOsGRLmRBqXYwoMRT1pM2DcogroPULNWs9T4u3xd7sRDKLXVG4eS_c7IcpoTIbVCWgnGZ9YG5CpytPz-F31JWTRlucnBJjPcY9QoqCs-x0uPxm3WQa536e1Kw8rCzirMzcoCU_G5lqx2jet7RDHNmzzxm6lyS0J-HXl5riATlVvACMB8BUrR3PgpYQJuT5WkvJ2Rd0X1FMmeQgpKkUjpJYXhCXEwpEFxw4M0tj9zg'], true),
  ('ocean-breeze-worry-stone', 'Ocean Breeze Worry Stone', 'Each piece is crafted with intention and a sprinkle of studio magic. Small, beautiful objects have the power to turn your daily ritual into a moment of pure creativity.', '"This piece was inspired by the quiet morning light hitting the studio floor. Every detail was mixed and finished by hand to capture that exact translucent quality." — Lucy', 2200, 'USD', 8, (select id from public.categories where slug = 'keychains-worry-stones'), array['https://lh3.googleusercontent.com/aida-public/AB6AXuCh4uQW5dvat_-BaRqYGdF2VU5TdmvPJHtQkPSgiGmP5q2MBW7-n1ggMJPxowLPcw8bp9LfxgEXhY0jJyorUZ9REdqrzPxJ3sIJhwQBGyHsSkoHXVMmQRK9y0gCIVn8MpGbNLTogKXJmSkv8tMVqU9DEs9NPcajvT4LyCG0XsEx1GpeBXVl03V3hei2L9SNfVsTHdzpvDnyDLUMDXH1_HaFaeTrS5CyhzMeXFTRqFxZYzC7idL0CYGHyQ'], true),
  ('minimalist-profile-tote', 'Minimalist Profile Tote', 'Each piece is crafted with intention and a sprinkle of studio magic. Small, beautiful objects have the power to turn your daily ritual into a moment of pure creativity.', '"This piece was inspired by the quiet morning light hitting the studio floor. Every detail was mixed and finished by hand to capture that exact translucent quality." — Lucy', 3400, 'USD', 15, (select id from public.categories where slug = 'tote-bags'), array['https://lh3.googleusercontent.com/aida-public/AB6AXuAWYoRN1hcxxRIOZX20NT7clPdw46wRUrgIanuL7ZNdoDS4aUO4Dlxo_50ZAuvc0Nkd66h06sqwBE1jcJKoecwoXX9xWZvmsK513OyZKpl5jdJOgAVQA5gZu0Bkk2XckhQRad6ESJ_jvtTxr7-IyGhX7EgGwLKDEeYBagunhSLG4s7gmsyLa9owpIAP-OiyWKIQB1IRyvut2DU_0cCqosGTsO4R6fssVRbibdxSOddEacese8oN2Zu0Mg'], true),
  ('monstera-trinket-dish', 'Monstera Trinket Dish', 'Each piece is crafted with intention and a sprinkle of studio magic. Small, beautiful objects have the power to turn your daily ritual into a moment of pure creativity.', '"This piece was inspired by the quiet morning light hitting the studio floor. Every detail was mixed and finished by hand to capture that exact translucent quality." — Lucy', 2600, 'USD', 6, (select id from public.categories where slug = 'keychains-worry-stones'), array['https://lh3.googleusercontent.com/aida-public/AB6AXuCMovsTmQ5y5KA1XQXzQHBGy0l1nYdKwDpZRnkmTs7842JxrevvM-pG3m82RJ_rmEpPECRWKT86y6_hw_cmlfBmyBJmYgaqagCoSxdf_rPCFqsyx-Zs1QcYcQm9tEANyQhQmXjuEbkqBI2VXcd6m-QpdJ44pJqZ7x6u385V9jEx5a3JMbv6Ft1JG3A_pAhTjB-nzMNNix2jeasulQmmM57RuTL4khlTqspX_Qpjp76vDh5CsHhpRjh1fQ'], true),
  ('botanical-sticker-pack', 'Botanical Sticker Pack', 'Each piece is crafted with intention and a sprinkle of studio magic. Small, beautiful objects have the power to turn your daily ritual into a moment of pure creativity.', '"This piece was inspired by the quiet morning light hitting the studio floor. Every detail was mixed and finished by hand to capture that exact translucent quality." — Lucy', 1000, 'USD', 40, (select id from public.categories where slug = 'stickers'), array['https://lh3.googleusercontent.com/aida-public/AB6AXuDT5L5upOksw2h3BOIMjilhTq8mspP3NoTC1VsH7I-h-RFaaZmYkQcz01X-DPeR8QYiDdaIxZDVRShcd5Pd4S4i0qtQE-LqwBVJW_qtBIWSS-0ovLsuHNs7xFsBOBdPNxmhD98GQIlOsu3qE6MoKQzyw7nl72pwQt2O_T8SIvQfKXpUaiZE0a0TNv4CHUSsbmDCQQfauUkMe8QBKcsVcqbsFBMQl2SC1Phx-2zNK_e57Z8FSM3hs7t3yg'], true),
  ('worry-stone-set', 'Worry Stone Set', 'Each piece is crafted with intention and a sprinkle of studio magic. Small, beautiful objects have the power to turn your daily ritual into a moment of pure creativity.', '"This piece was inspired by the quiet morning light hitting the studio floor. Every detail was mixed and finished by hand to capture that exact translucent quality." — Lucy', 3200, 'USD', 5, (select id from public.categories where slug = 'keychains-worry-stones'), array['https://lh3.googleusercontent.com/aida-public/AB6AXuCtrEDlidBC7Hx4xjLlX54AOEcPWVUvaclvQQ40w1DYnNdgdFBqUDToXsMpbVjJa2kxz6dEl2L1i8aQk4gfo1_GR1HJza2TQyT5iOh4kU1_Rs9_EDCMXCZCRerivH_Hgdf56nktLaUXWRQ7jP95KfiY3E-NH1hMQ2sMHPdNCpc0IteG_uIvcr0hz6AHT8jMR45-78a00NwHCoiPs0Ee4LdVCvXQ5bBv5av5x45gZ95ghRCCjiMA1mNpoQ'], true),
  ('minimalist-tote', 'Minimalist Tote', 'Each piece is crafted with intention and a sprinkle of studio magic. Small, beautiful objects have the power to turn your daily ritual into a moment of pure creativity.', '"This piece was inspired by the quiet morning light hitting the studio floor. Every detail was mixed and finished by hand to capture that exact translucent quality." — Lucy', 1800, 'USD', 9, (select id from public.categories where slug = 'tote-bags'), array['https://lh3.googleusercontent.com/aida-public/AB6AXuAWYoRN1hcxxRIOZX20NT7clPdw46wRUrgIanuL7ZNdoDS4aUO4Dlxo_50ZAuvc0Nkd66h06sqwBE1jcJKoecwoXX9xWZvmsK513OyZKpl5jdJOgAVQA5gZu0Bkk2XckhQRad6ESJ_jvtTxr7-IyGhX7EgGwLKDEeYBagunhSLG4s7gmsyLa9owpIAP-OiyWKIQB1IRyvut2DU_0cCqosGTsO4R6fssVRbibdxSOddEacese8oN2Zu0Mg'], true),
  ('sticker-sheet-dreamy', 'Sticker Sheet ''Dreamy''', 'Each piece is crafted with intention and a sprinkle of studio magic. Small, beautiful objects have the power to turn your daily ritual into a moment of pure creativity.', '"This piece was inspired by the quiet morning light hitting the studio floor. Every detail was mixed and finished by hand to capture that exact translucent quality." — Lucy', 800, 'USD', 30, (select id from public.categories where slug = 'stickers'), array['https://lh3.googleusercontent.com/aida-public/AB6AXuAq1RSQwZRKbQKzeQBaiGwvQQpVRYEbPFxsa5HL8nn71M2yb394OGRLHSnpDLJXY6IWDm8NY1ra79cD--1Yc0eM2VXOQTRac13ADnKvicuFVx7b91wbz8Fd_GYmiMa2pubXjcaB8boD_0P5K7SYKz--pzstDwLoJmQOUAZmEiqv9CkhrxwG1Ni_YKflzPYUWtlIco-eKunLguljpWEcLnsxzBdQDyg5LbiP_xoqsjdIp04Ob5csCfVuNQ'], true),
  ('ceramic-paint-palette', 'Ceramic Paint Palette', 'Each piece is crafted with intention and a sprinkle of studio magic. Small, beautiful objects have the power to turn your daily ritual into a moment of pure creativity.', '"This piece was inspired by the quiet morning light hitting the studio floor. Every detail was mixed and finished by hand to capture that exact translucent quality." — Lucy', 4500, 'USD', 4, (select id from public.categories where slug = 'stationery'), array['https://lh3.googleusercontent.com/aida-public/AB6AXuBkipR38ayssJ8hepc2EC7n58VyUmdhmuXqG7ZBlM6oyrL7trohten8pIYjXBEvdAqsmg0denrzLAmS_ZYfGoajdML7F9B0A9IhWctGCqY9bX11Mc7NKhngw1-nvYoPxiYHPdGekDcqXa_8hMu2gMXbLZiWluMRlTuiEtCo2VllhCKZ-df0lCoExKvYRGjGFCqujQYSDVYF-A23CJ2n1BHJAT0U8FzJkINYuNZ6tTFjdqxwO8BsTtlPAw'], true),
  ('hand-bound-journal', 'Hand-Bound Journal', 'Each piece is crafted with intention and a sprinkle of studio magic. Small, beautiful objects have the power to turn your daily ritual into a moment of pure creativity.', '"This piece was inspired by the quiet morning light hitting the studio floor. Every detail was mixed and finished by hand to capture that exact translucent quality." — Lucy', 3800, 'USD', 7, (select id from public.categories where slug = 'bookmarks'), array['https://lh3.googleusercontent.com/aida-public/AB6AXuCE3eLndsU7Mmv_N_WVoUi-4EOO_HAVOq0FkmTXYcwb4JXzyAMYwuYPCPBZgUxiPVBd6L0HKw5W2xaW0lNQz3clT1nhRGDFTyL9epQ1FvJvcuywi-qMFFdNeFQZCHsL6tbFAm87FFK0tJAss6oV9L_Xo0CfCFzjAjLMYiNi1xENC9XmdaffBuhRPKjVy7Li1QYOXQ-sOkDKivhcJVOvd-RS7mXiP6MBRHbw4Dt9xFyCLFQfcpWqinHfkQ'], true);
